id: alien4cloud-supervision
name: Alien4Cloud Supervision
version: ${project.version}
description: >
  Supervision Plugin for Alien4Cloud
configuration_class: alien4cloud.plugin.supervision.PluginConfiguration
component_descriptors:
  - bean_name: kafka-logger
    name: Logger Supervision
    description: >
      Logger that send events to Supervision
  - bean_name: kubernetes-supervision-modifier
    name: Kubernetes Supervion Modifier.
    description: >
      This topology modifier adds supervision annotations to kubernetes resources.
      Insert this modifier to post-matched-node-setup phase.
